ifeq ($(origin CC),default)
CC	= gcc
endif
ifeq ($(origin AS),default)
AS	= gcc
endif
ifeq ($(origin AR),default)
AR	= ar rcs
endif
ifeq ($(origin LD),default)
LD	= ld
endif

CONFIG_PAL_STACK_PROTECTOR = n
# CONFIG_PAL_STACK_PROTECTOR = y
