MAKEFILE_CONFIGS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

ifeq ($(origin CC),default)
CC	= gcc
endif
ifeq ($(origin AS),default)
AS	= gcc
endif
ifeq ($(origin AR),default)
AR	= ar
endif
ifeq ($(origin ARFLAGS),default)
ARFLAGS = rcs
endif
ifeq ($(origin LD),default)
LD	= ld
endif
ifeq ($(origin CXX),default)
CXX = g++
endif
OBJCOPY ?= objcopy

SYS ?= $(shell $(CC) -dumpmachine)
export SYS

DEBUG ?=
export DEBUG

MAKEFILE_CONFIGS_INCLUDED = y
include $(MAKEFILE_CONFIGS_DIR)/Makefile.Host
