ifeq ($(MAKEFILE_MANIFEST_DIR),)
$(error include Makefile.manifest before $(lastword $(MAKEFILE_LIST)))
endif

MAKEFILE_TEST_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

PALDIR  = $(MAKEFILE_TEST_DIR)/Pal/src
SHIMDIR = $(MAKEFILE_TEST_DIR)/LibOS/shim/src
RUNTIME = $(MAKEFILE_TEST_DIR)/Runtime

CFLAGS += -std=gnu99

# TODO: enable -Wunused-result
CFLAGS += -Wno-unused-result

CFLAGS-libos = -I$(SHIMDIR)/../include -L$(SHIMDIR)/../../glibc-build/libos

CFLAGS-libos-debug = -I$(SHIMDIR)/../include -I$(PALDIR)/../include/pal -I$(PALDIR)/../lib -fno-builtin -nostdlib
CXXFLAGS-libos-debug = -I$(SHIMDIR)/../include -I$(PALDIR)/../include/pal -I$(PALDIR)/../lib -fno-builtin -nostdlib
LDFLAGS-libos-debug = -L$(SHIMDIR) -L$(PALDIR)/host/$(PAL_HOST) -Wl,-rpath-link=$(abspath $(RUNTIME)) -lpal -lsysdb_debug

.PHONY: all
all: pal_loader $(target) | $(exec_target) $(call expand_target_to_sgx,$(exec_target)) $(call expand_target_to_sig,$(exec_target))

.PHONY: sgx-tokens
sgx-tokens: $(call expand_target_to_token,$(exec_target))

ifeq ($(ABSPATH_IN_MANIFEST),yes)
manifest_rules ?= \
	-e 's:\$$(PAL):$(abspath $(RUNTIME))/pal_loader:g' \
	-e 's:\$$(PWD):$(PWD):g' \
	-e 's:\$$(BIN):$(subst .manifest,,$(notdir $@)):g' \
	-e 's:\$$(SHIMPATH):$(abspath $(RUNTIME))/libsysdb.so:g' \
	-e 's:\$$(LIBCDIR):$(abspath $(RUNTIME)):g' \
	$(extra_rules)
else
manifest_rules ?= \
	-e 's:\$$(PAL):$(abspath $(RUNTIME))/pal_loader:g' \
	-e 's:\$$(PWD):$(PWD):g' \
	-e 's:\$$(BIN):$(subst .manifest,,$(notdir $@)):g' \
	-e 's:\$$(SHIMPATH):$(RUNTIME)/libsysdb.so:g' \
	-e 's:\$$(LIBCDIR):$(RUNTIME):g' \
	$(extra_rules)
endif

pal_loader:
	ln -sf $(RUNTIME)/pal_loader

.PHONY: clean
clean: $(clean-extra)
	rm -rf pal_loader $(exec_target) $(target) $(wildcard *.d) .output.* \
	       *.sig *.token *.manifest.sgx
