.PHONY: all
all:

.PHONY: clean
clean:
	$(RM) *.a *.o *.so *.so.* pal-* .compiler-options

.PHONY: distclean
distclean: clean

.PHONY: format
format:

.PHONY: test
test:

.PHONY: sgx-tokens
sgx-tokens:
