#!/bin/sh

set -e

cd "$(git rev-parse --show-toplevel)"

shellcheck "$@" \
    Examples/bash/scripts/bash_test.sh \
    Examples/common_tools/benchmark-http.sh \
    Examples/python-simple/run-tests.sh \
    Pal/src/host/Linux-SGX/debugger/gdb \
    Runtime/pal_loader \
    Scripts/clean-check \
    Scripts/clean-check-prepare \
    Scripts/clean-check-test-copy \
    Scripts/download \
    Scripts/gitignore-test \
    .ci/run-pylint \
    .ci/run-shellcheck
