FROM {{image}} as unsigned_image

COPY gsc-signer-key.pem /gsc-signer-key.pem

RUN python3 -B /sign_manifests.py

FROM {{image}}

COPY --from=unsigned_image *.sig ./
COPY --from=unsigned_image *.sgx ./

RUN rm signature_order.txt sign_manifests.py /graphene/signer/pal-sgx-sign /graphene/signer/pal_sgx_sign.py
