# We sign the image in a multi-stage build to ensure that the signing key is never part of the
# final image.
FROM {{image}} as unsigned_image

COPY gsc-signer-key.pem /gsc-signer-key.pem

RUN python3 -B sign_manifests.py #TODO: missing arg here?

FROM {{image}}

COPY --from=unsigned_image {{working_dir}}*.sig ./
COPY --from=unsigned_image {{working_dir}}*.sgx ./

RUN rm sign_manifests.py /graphene/python/graphene-sgx-sign /graphene/python/graphenelibos/sgx_sign.py
