include ../../../makevars.mk

testcases = $(shell cd $(ROOTDIR); \
	./runltp_xml.py $(RUNLTPOPTS) -c ltp.cfg --list-executables $(LTPSCENARIO))

exec_target = $(testcases)
manifests = $(addsuffix .manifest,$(testcases))
target = $(manifests) $(testcases) etc/nsswitch.conf etc/passwd

include $(ROOTDIR)/Makefile.Test

etc/nsswitch.conf:
	mkdir -p etc
	printf "passwd: compat\ngroup: compat\nshadow: compat\nhosts: files\n" > $@

etc/passwd:
	mkdir -p etc
	printf "root:x:0:0:root:/root:/bin/bash\nnobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin\n" > $@

.PHONY: sgx-tokens
sgx-tokens: $(call expand_target_to_token,$(testcases))
