#!/usr/bin/env python3

import os
import pathlib
import sys

fspath = getattr(os, 'fspath', str)
sys.path.insert(0,
    fspath((pathlib.Path(__file__).parent / '../../python').resolve()))

import graphenelibos.manifest
graphenelibos.manifest.main()
