/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: aesm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "aesm.pb-c.h"
void   request__init_quote_request__init
                     (Request__InitQuoteRequest         *message)
{
  static Request__InitQuoteRequest init_value = REQUEST__INIT_QUOTE_REQUEST__INIT;
  *message = init_value;
}
void   request__get_quote_request__init
                     (Request__GetQuoteRequest         *message)
{
  static Request__GetQuoteRequest init_value = REQUEST__GET_QUOTE_REQUEST__INIT;
  *message = init_value;
}
void   request__init
                     (Request         *message)
{
  static Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init_quote_response__init
                     (Response__InitQuoteResponse         *message)
{
  static Response__InitQuoteResponse init_value = RESPONSE__INIT_QUOTE_RESPONSE__INIT;
  *message = init_value;
}
void   response__get_quote_response__init
                     (Response__GetQuoteResponse         *message)
{
  static Response__GetQuoteResponse init_value = RESPONSE__GET_QUOTE_RESPONSE__INIT;
  *message = init_value;
}
void   response__init
                     (Response         *message)
{
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request__init_quote_request__field_descriptors[1] =
{
  {
    "timeout",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Request__InitQuoteRequest, has_timeout),
    offsetof(Request__InitQuoteRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__init_quote_request__field_indices_by_name[] = {
  0,   /* field[0] = timeout */
};
static const ProtobufCIntRange request__init_quote_request__number_ranges[1 + 1] =
{
  { 9, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__init_quote_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.InitQuoteRequest",
  "InitQuoteRequest",
  "Request__InitQuoteRequest",
  "",
  sizeof(Request__InitQuoteRequest),
  1,
  request__init_quote_request__field_descriptors,
  request__init_quote_request__field_indices_by_name,
  1,  request__init_quote_request__number_ranges,
  (ProtobufCMessageInit) request__init_quote_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__get_quote_request__field_descriptors[8] =
{
  {
    "report",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quote_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, quote_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, spid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Request__GetQuoteRequest, has_nonce),
    offsetof(Request__GetQuoteRequest, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig_rl",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Request__GetQuoteRequest, has_sig_rl),
    offsetof(Request__GetQuoteRequest, sig_rl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buf_size",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, buf_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qe_report",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Request__GetQuoteRequest, has_qe_report),
    offsetof(Request__GetQuoteRequest, qe_report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Request__GetQuoteRequest, has_timeout),
    offsetof(Request__GetQuoteRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__get_quote_request__field_indices_by_name[] = {
  5,   /* field[5] = buf_size */
  3,   /* field[3] = nonce */
  6,   /* field[6] = qe_report */
  1,   /* field[1] = quote_type */
  0,   /* field[0] = report */
  4,   /* field[4] = sig_rl */
  2,   /* field[2] = spid */
  7,   /* field[7] = timeout */
};
static const ProtobufCIntRange request__get_quote_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor request__get_quote_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.GetQuoteRequest",
  "GetQuoteRequest",
  "Request__GetQuoteRequest",
  "",
  sizeof(Request__GetQuoteRequest),
  8,
  request__get_quote_request__field_descriptors,
  request__get_quote_request__field_indices_by_name,
  2,  request__get_quote_request__number_ranges,
  (ProtobufCMessageInit) request__get_quote_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[2] =
{
  {
    "initQuoteReq",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, initquotereq),
    &request__init_quote_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getQuoteReq",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, getquotereq),
    &request__get_quote_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = getQuoteReq */
  0,   /* field[0] = initQuoteReq */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  2,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t response__init_quote_response__error_code__default_value = 1u;
static const ProtobufCFieldDescriptor response__init_quote_response__field_descriptors[3] =
{
  {
    "errorCode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Response__InitQuoteResponse, errorcode),
    NULL,
    &response__init_quote_response__error_code__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetInfo",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__InitQuoteResponse, has_targetinfo),
    offsetof(Response__InitQuoteResponse, targetinfo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__InitQuoteResponse, has_gid),
    offsetof(Response__InitQuoteResponse, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__init_quote_response__field_indices_by_name[] = {
  0,   /* field[0] = errorCode */
  2,   /* field[2] = gid */
  1,   /* field[1] = targetInfo */
};
static const ProtobufCIntRange response__init_quote_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor response__init_quote_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.InitQuoteResponse",
  "InitQuoteResponse",
  "Response__InitQuoteResponse",
  "",
  sizeof(Response__InitQuoteResponse),
  3,
  response__init_quote_response__field_descriptors,
  response__init_quote_response__field_indices_by_name,
  1,  response__init_quote_response__number_ranges,
  (ProtobufCMessageInit) response__init_quote_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t response__get_quote_response__error_code__default_value = 1u;
static const ProtobufCFieldDescriptor response__get_quote_response__field_descriptors[3] =
{
  {
    "errorCode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Response__GetQuoteResponse, errorcode),
    NULL,
    &response__get_quote_response__error_code__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quote",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__GetQuoteResponse, has_quote),
    offsetof(Response__GetQuoteResponse, quote),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qe_report",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__GetQuoteResponse, has_qe_report),
    offsetof(Response__GetQuoteResponse, qe_report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__get_quote_response__field_indices_by_name[] = {
  0,   /* field[0] = errorCode */
  2,   /* field[2] = qe_report */
  1,   /* field[1] = quote */
};
static const ProtobufCIntRange response__get_quote_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor response__get_quote_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.GetQuoteResponse",
  "GetQuoteResponse",
  "Response__GetQuoteResponse",
  "",
  sizeof(Response__GetQuoteResponse),
  3,
  response__get_quote_response__field_descriptors,
  response__get_quote_response__field_indices_by_name,
  1,  response__get_quote_response__number_ranges,
  (ProtobufCMessageInit) response__get_quote_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "initQuoteRes",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, initquoteres),
    &response__init_quote_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getQuoteRes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, getquoteres),
    &response__get_quote_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = getQuoteRes */
  0,   /* field[0] = initQuoteRes */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
