# Start with 16.04
FROM ubuntu:16.04

# Add steps here to set up dependencies



# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
