#!/bin/bash

DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
GDB_SCRIPT=$DIR/pal-gdb.py
GDB_SO=$DIR/sgx_gdb.so
if [ -z "$INSIDE_EMACS" ]; then
	set -x
fi

LD_PRELOAD=$GDB_SO gdb -iex "add-auto-load-safe-path $GDB_SCRIPT" "$@"
