ifeq ($(SYS),)
$(error include Makefile.config before $(lastword $(MAKEFILE_LIST)))
endif

ifeq ($(MAKEFILE_MANIFEST_DIR),)
$(error include manifest.mk before $(lastword $(MAKEFILE_LIST)))
endif

SCRIPTS_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
SHIM_TEST_DIR = $(SCRIPTS_DIR)/../LibOS/shim/test

PALDIR  = $(abspath $(SCRIPTS_DIR)/../Pal/src)
SHIMDIR = $(abspath $(SCRIPTS_DIR)/../LibOS/shim)
RUNTIME = $(abspath $(SCRIPTS_DIR)/../Runtime)

include $(SCRIPTS_DIR)/Makefile.rules

CFLAGS-libos = -I$(SHIMDIR)/include -L$(SHIMDIR)/../glibc-build/libos

CFLAGS-libos-debug = -I$(SHIMDIR)/include -I$(PALDIR)/../include/pal -I$(PALDIR)/../include/lib -fno-builtin -nostdlib
CXXFLAGS-libos-debug = -I$(SHIMDIR)/include -I$(PALDIR)/../include/pal -I$(PALDIR)/../include/lib -fno-builtin -nostdlib
LDFLAGS-libos-debug = -L$(SHIMDIR)/src -L$(PALDIR)/host/$(PAL_HOST) -Wl,-rpath-link=$(abspath $(RUNTIME)) -lpal -lsysdb_debug

.PHONY: all
ifeq ($(findstring x86_64,$(SYS))$(findstring linux,$(SYS)),x86_64linux)
all: $(exec_target) | $(all_manifests) $(call expand_target_to_sgx,$(all_manifests)) $(call expand_target_to_sig,$(all_manifests))
else
all:
endif

.PHONY: sgx-tokens
sgx-tokens: $(call expand_target_to_token,$(all_manifests))

manifest_rules = \
	-Darch_libdir=$(ARCH_LIBDIR) \
	$(extra_rules)

ifeq ($(filter %clean,$(MAKECMDGOALS)),)
include $(wildcard *.d)
ifeq ($(SGX),1)
include $(addsuffix .manifest.sgx.d,$(patsubst %.manifest,%,$(all_manifests)))
endif
endif

.PHONY: clean
clean: $(clean-extra)
	$(RM) -r $(gen_manifests) $(exec_target) $(wildcard *.d) .output.* \
	       *.sig *.token *.manifest.sgx

.PHONY: distclean
distclean: clean
