# By default, Graphene runs the system Python 3.5 executable.
PYTHONVERSION ?= python3.5
PYTHONPATH ?= /usr

PYTHONHOME := $(PYTHONPATH)/lib/$(PYTHONVERSION)
PYTHONEXEC := $(PYTHONPATH)/bin/$(PYTHONVERSION)
PYTHONDISTHOME := $(PYTHONPATH)/lib/python3/dist-packages
PYTHONSHORTVERSION := $(subst python,,$(subst .,,$(PYTHONVERSION)))
