#!/bin/sh

set -e

# A wrapper for running pytest, either manually or through a Makefile.
# Usage:
#    SGX=1 .../run-pytest

PYTHONPATH="$(realpath "$(dirname "$0")/..")/Scripts:$PYTHONPATH"
export PYTHONPATH

exec python3 -m pytest "$@"
