#!/bin/bash

JAVA_FLAGS="-Xmx4m -Xms1m -XX:NewSize=256k -XX:MaxNewSize=1m -Xss1m -XX:+UseSerialGC -XX:-UsePerfData -XX:+DisableExplicitGC -XX:PermSize=1m -XX:MaxPermSize=4m -XX:MinHeapFreeRatio=0 -XX:MaxHeapFreeRatio=30"

if [ "$1" = "-native" ]; then
	shift
	`make java_home`/bin/java $JAVA_FLAGS $*
elif [ "$1" = "-gdb" ]; then
	shift
	./java.manifest -gdb $JAVA_FLAGS $*
else
	./java.manifest $JAVA_FLAGS $*
fi
