#!/bin/bash

JAVA_FLAGS="-Xmx16m -Xss4m -XX:+UseSerialGC -XX:+DisableExplicitGC -XX:MaxPermSize=0"
BENCH_ARGS="-jar jmh/target/benchmarks.jar -wi 3 -i 10 -f 0 -tu us -Djmh.ignoreLock=true"

if [ "$1" = "-gdb" ]; then
	shift
	gdb --args ../libpal.so java.manifest $JAVA_FLAGS $* $BENCH_ARGS
elif [ "$1" = "-native" ]; then
	shift
	`make java_home`/bin/java $JAVA_FLAGS $* $BENCH_ARGS
else
	./java.manifest $JAVA_FLAGS $* $BENCH_ARGS
fi
