#!/usr/bin/env python3

# This is just a wrapper that provides the cmdline tool. All code should go
# into pal_sgx_sign.py.

# pylint: disable=invalid-name

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from pal_sgx_sign import main # pylint: disable=import-error,wrong-import-position

sys.exit(main())
