#!/usr/bin/env python3
# pylint: disable=invalid-name,import-error,wrong-import-position

import sys
import os
import pathlib
import warnings

# this is needed, so import generated_offsets works as backup from main python package
sys.path.insert(0, os.fspath(pathlib.Path(__file__).parent.parent))

sys.path.insert(0, os.fspath((pathlib.Path(__file__) / '../../../../../../python').resolve()))
from grapheneos.sgx_sign import main

warnings.warn(
    'pal-sgx-sign is deprecated, please install graphene and use graphene-sgx-sign',
    DeprecationWarning)
sys.exit(main())
