#!/usr/bin/env python3
# pylint: disable=invalid-name,import-error,wrong-import-position

import sys
import os
import pathlib

try:
    fspath = os.fspath
except AttributeError:
    fspath = str

# this is needed, so import generated_offsets works as backup from main python package
sys.path.insert(0, fspath(pathlib.Path(__file__).parent.parent))

sys.path.insert(0, fspath((pathlib.Path(__file__) / '../../../../../../python').resolve()))
from graphenelibos.sgx_get_token import main

sys.exit(main())
