manifests = $(patsubst ../../../%.template,%,$(wildcard ../../../*.manifest.template)) manifest
lmbench_tests = lat_syscall lat_connect lat_fcntl \
		lat_select lat_fs lat_mmap lat_fifo lat_mem_rd lat_msg \
		lat_tcp lat_udp lat_unix_connect lat_pagefault \
		bw_tcp bw_mem bw_unix lat_proc lat_ctx lat_rpc \
		lat_unix lat_sig lat_http lat_pipe \
		bw_pipe bw_file_rd bw_mmap_rd lmhttp lmdd \
		sh.manifest hello.manifest

exec_target = $(lmbench_tests)
target = $(manifests)

level = ../../../../../
include ../../../../../Makefile

sh.manifest.sgx: /tmp/hello

/tmp/hello: hello
	cp -f $< $@

$(addsuffix .template,$(manifests)): %: ../../../%
	ln -sf $< $@
