pipeline {
        agent any
        stages {
                stage('Build') {
                    steps {
                        sh '''
                            make
                           '''
                    }
                }
                stage('Test') {
                    steps {
                        sh '''
                            cd LibOS/shim/test/apps/gcc
                            make regression
                           '''
                        sh '''
                            cd LibOS/shim/test/apps/python
                            make regression
                            '''
                        input 'Tests complete. Do you wish to deploy?'
                    }
                }
                stage('Deploy') {
                    steps {
                        sh 'echo Deploying code'
                    }
                }
        }
        post {
                success {
                        echo 'Deployment successful'
                }
                failure {
                        echo 'Failure while on the pipeline'
                }
                unstable {
                        echo 'Pipeline marked as "unstable"'
                }
        }
}

