.\" $Id$
.TH BW_TCP 1 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
bw_tcp \- time data movement through TCP/IP sockets
.SH SYNOPSIS
.B bw_tcp
.I -s
.sp .5
.B bw_tcp
.I hostname [transfersize]
.sp .5
.B bw_tcp
.I -hostname
.SH DESCRIPTION
.B bw_tcp
is a client/server program that moves data over a TCP/IP socket.  Nothing is
done with the data on either side; the data is moved in 64KB chunks.
.PP
.B bw_tcp
has three forms of usage: as a server (-s), as a client (bw_tcp localhost), and
as a shutdown (bw_tcp -localhost).
.PP
The default amount of data is 3MB.  The client form may specify a different
amount of data.  Specifications may end with ``k'' or ``m'' to mean
kilobytes (* 1024) or megabytes (* 1024 * 1024).
.SH OUTPUT
Output format is
.ft CB
Socket bandwidth using localhost: 2.32 MB/sec
.ft
.SH MEMORY UTILIZATION
This benchmark can move up to six times the requested memory per process
when run through the loopback device.
There are two processes, the sender and the receiver.
Most Unix
systems implement the read/write system calls as a bcopy from/to kernel space
to/from user space.  Bcopy will use 2-3 times as much memory bandwidth:
there is one read from the source and a write to the destionation.  The
write usually results in a cache line read and then a write back of
the cache line at some later point.  Memory utilization might be reduced
by 1/3 if the processor architecture implemented "load cache line"
and "store cache line" instructions (as well as getcachelinesize).
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation 
and Silicon Graphics, Inc.
.SH SEE ALSO
lmbench(8), read(2), write(2), socket(2), bind(2), connect(2).
