.\" $Id$
.TH LAT_SIG 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_sig \- measure signal handling latencies
.SH SYNOPSIS
.B lat_sig
.I "install|catch|prot"
.I <file>
.SH DESCRIPTION
.B lat_sig
measures the time to install or catch signals.
It can also measure the time to handle a memory protection fault.
.B lat_sig
only requires the 
.I file
argument when measuring protection fault latency.
.SH OUTPUT
Output formats are like so:
.ft CB
.br
Signal handler installation: 9.564 microseconds
.br
Signal handler overhead: 33.484 microseconds
.br
Protection fault: 11.925 microseconds
.ft
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8), sigaction(2), kill(2), mmap(2).
