.\" $Id$
.TH LAT_SELECT 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_select - time simple entry into the operating system
.SH SYNOPSIS
.B lat_select
.I "tcp|file"
[
.I n
]
.SH DESCRIPTION
.B lat_select
times how long it takes to 
.I select
on
.B n
file descriptors.
.B lat_select
can either 
.I select
on local files, or TCP network connections.
.SH OUTPUT
Output format depends on whether 
.B lat_select
is testing local files or network connections.
In either case it reports the number of descriptors
and the average latency in microseconds.
Example output for 
.B lat_select
on files is:
.sp
.ft CB
Select on 200 fd's: 67 microseconds
.ft
.PP
or for network connections:
.ft CB
Select on 200 tcp fd's: 117 microseconds
.ft
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8), select(2), dup(2), open(2).
