.\" $Id$
.TH LAT_TCP 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_tcp \- measure interprocess communication latency via TCP/IP
.SH SYNOPSIS
.B lat_tcp
.I -s
.sp .5
.B lat_tcp
.I hostname
.sp .5
.B lat_tcp
.I -hostname
.SH DESCRIPTION
.B lat_tcp
is a client/server program that measures interprocess
communication latencies.  The benchmark passes a token back and forth between
the two processes (this sort of benchmark is frequently referred to as a
``hot potato'' benchmark).  No other work is done in the processes.
.PP
.B lat_tcp
has three forms of usage: as a server (lat_tcp -s), 
as a client (lat_tcp localhost), and
as a shutdown (lat_tcp -localhost).
.SH OUTPUT
The reported time is in microseconds per round trip and includes the total
time, i.e., the context switching overhead is included.
Output format is like so
.sp
.ft CB
TCP latency using localhost: 700 microseconds
.ft
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8), read(2), write(2), socket(2), bind(2), connect(2).
