.\" $Id$
.TH LAT_PAGEFAULT 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_pagefault \- measure the cost of pagefaulting pages from a file
.SH SYNOPSIS
.B lat_pagefault
.I file
[
.I file....
]
.SH DESCRIPTION
.B lat_pagefault
times how fast a page of a file can be faulted in.  The file is flushed from 
(local) memory by using the \f(CBmsync()\fP interface with the invalidate
flag set.  (Note that NFS does not send this over the wire so this makes
for a handy way to measure the cost of going across the wire.)
.PP
The benchmark maps in the entire file and the access pages backwards using
a stride of 256K kilobytes.
.SH OUTPUT
Output format is below; it prints the average cost of page faulting a page.
.sp
.ft CB
Pagefaults on <file>: <d> usecs
.ft
.SH BUGS
Using a stride of 256K may be a bad idea because SCSI controllers
may have caches bigger than that.
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8), mmap(2), munmap(2).
