.\" $Id$
.TH LAT_MMAP 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_mmap \- costs of mmapping and unmmapping varying file sizes
.SH SYNOPSIS
.B lat_mmap
.I size
.I file
.SH DESCRIPTION
.B lat_mmap
times how fast a mapping can be made and unmade.  This is useful because it
is a fundemental part of processes that use SunOS style shared libraries
(the libraries are mapped in at process start up time and unmapped at 
process exit).
.PP
The benchmark maps in and unmaps the first \fIsize\fP bytes of the file
repeatedly and reports the average time for one mapping/unmapping.  
.PP
The size
specification may end with ``k'' or ``m'' to mean
kilobytes (* 1024) or megabytes (* 1024 * 1024).
.SH OUTPUT
Output format is \f(CB"%0.2f %d\\n", megabytes, usecs\fP, i.e.,
.sp
.ft CB
8.00 1200
.ft
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8), open(2), mmap(2), munmap(2).
