.\" $Id$
.TH LOOP_O 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
loop_o \- report timing overhead
.SH SYNOPSIS
.B loop_o
.SH DESCRIPTION
.B loop_o
reports the 
.IR for ()
loop overhead associated with measuring timing intervals.
This is critical mostly for experiments which measure very
fast operations, such as memory loads, and which haven't
been designed to minimize the loop overhead effects by
some form of manual loop unrolling.
.SH OUTPUT
The output is reported in microseconds as an float:
.IP ""
\fC0.000005\fR
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8), lmbench(3), timing(3).
