.\" $Id$
.TH TIMING_O 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
timing_o \- report timing overhead
.SH SYNOPSIS
.B timing_o
.SH DESCRIPTION
.B timing_o
reports the overhead associated with measuring timing intervals.
.SH OUTPUT
The output is reported in microseconds as an integer:
.IP ""
\fC7\fR
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8), lmbench(3), timing(3).
